"""
GDELT Planner + Report Generator

Planner: Understands user intent and generates a structured query plan.
Report Generator: Summarizes JSON data into natural language insights.

Both use LangChain ChatOpenAI for LLM integration.
"""

import os
import json
import re
import asyncio

from typing import List, Dict, Any, Optional

import httpx
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_openai import ChatOpenAI




# ---------------------------------------------------------------------------
# Data Models
# ---------------------------------------------------------------------------

class QueryStep(BaseModel):
    """A single data query step in the execution plan."""
    type: str = Field(..., description="Query type: dashboard, timeseries, geo, events, overview, top_events, hot_events, daily_brief, news_context, event_detail")
    params: Dict[str, Any] = Field(default_factory=dict, description="Parameters for the query")


class QueryPlan(BaseModel):
    """Structured plan generated by the Planner."""
    intent: str = Field(..., description="Brief description of user intent")
    thinking: Optional[str] = Field(None, description="AI reasoning for tool selection")
    time_range: Optional[Dict[str, str]] = Field(None, description="Resolved date range {start, end} if applicable")
    steps: List[QueryStep] = Field(..., description="Ordered list of queries to execute")
    visualizations: List[str] = Field(..., description="Recommended visualizations: stats_cards, timeline, map, heatmap, event_table, report")
    report_prompt: Optional[str] = Field(None, description="Optional prompt for AI report generation")


class ReportResult(BaseModel):
    """AI-generated report based on query results."""
    summary: str = Field(..., description="Executive summary")
    key_findings: List[str] = Field(default_factory=list, description="Bullet point key findings")


# ---------------------------------------------------------------------------
# LLM Builder (shared between Planner and Report)
# ---------------------------------------------------------------------------

def build_llm(config: Optional[Dict[str, Any]] = None) -> ChatOpenAI:
    """Initialize LLM from environment or runtime config."""
    cfg = config or {}
    provider = cfg.get("provider", os.getenv("LLM_PROVIDER", "kimi")).lower()

    configs = {
        "kimi": {
            "api_key": cfg.get("api_key", os.getenv("KIMI_CODE_API_KEY", os.getenv("MOONSHOT_API_KEY", ""))),
            "base_url": cfg.get("base_url", os.getenv("LLM_BASE_URL", "https://api.moonshot.cn/v1")),
            "model": cfg.get("model", os.getenv("LLM_MODEL", "kimi-k2-0905-preview")),
        },
        "moonshot": {
            "api_key": cfg.get("api_key", os.getenv("MOONSHOT_API_KEY", "")),
            "base_url": cfg.get("base_url", os.getenv("LLM_BASE_URL", "https://api.moonshot.cn/v1")),
            "model": cfg.get("model", os.getenv("LLM_MODEL", "kimi-k2-0905-preview")),
        },
        "claude": {
            "api_key": cfg.get("api_key", os.getenv("ANTHROPIC_API_KEY", "")),
            "base_url": cfg.get("base_url", os.getenv("LLM_BASE_URL", "https://api.anthropic.com/v1")),
            "model": cfg.get("model", os.getenv("LLM_MODEL", "claude-3-5-sonnet-20241022")),
        },
        "openai": {
            "api_key": cfg.get("api_key", os.getenv("OPENAI_API_KEY", "")),
            "base_url": cfg.get("base_url", os.getenv("LLM_BASE_URL", "https://api.openai.com/v1")),
            "model": cfg.get("model", os.getenv("LLM_MODEL", "gpt-4o")),
        },
    }

    provider_cfg = configs.get(provider, configs["kimi"])

    if not provider_cfg["api_key"]:
        raise ValueError(f"API key not set for provider: {provider}")

    # Kimi Coding API headers
    async def _inject_claude_headers(request: httpx.Request):
        request.headers["User-Agent"] = "claude-code/1.0"
        request.headers["X-Client-Name"] = "claude-code"

    http_async_client = httpx.AsyncClient(
        event_hooks={"request": [_inject_claude_headers]}
    )

    return ChatOpenAI(
        api_key=provider_cfg["api_key"],
        base_url=provider_cfg["base_url"],
        model=provider_cfg["model"],
        temperature=0.1,
        max_tokens=2048,
        http_async_client=http_async_client,
    )


# ---------------------------------------------------------------------------
# Planner
# ---------------------------------------------------------------------------

PLANNER_SYSTEM_PROMPT = """You are GDELT AI Analyst. Your job is to understand the user's request, decide which data tools to use, and explain your reasoning.

Output ONLY raw JSON. Do NOT use markdown, do NOT wrap in code blocks.

JSON schema:
{
  "thinking": "Your reasoning: what the user wants, why you chose these tools, what you expect to find",
  "intent": "short description of user intent",
  "time_range": {"start": "YYYY-MM-DD", "end": "YYYY-MM-DD"} or null,
  "steps": [
    {"type": "QUERY_TYPE", "params": {...}}
  ],
  "visualizations": ["event_table", "report"],
  "report_prompt": "prompt for AI analysis of the results"
}

Available tools:
- events: {query, start_date, end_date, location_hint, event_type, actor, limit} — broad keyword/actor/region search
- event_detail: {fingerprint} — specific event by fingerprint or EVT-ID
- similar_events: {seed_event_id} — find similar events (pair with event_detail)
- hot_events: {query_date, top_n} — hottest events on a single day (pre-computed or real-time)
- top_events: {start_date, end_date, region_filter, event_type, top_n} — top events across a date range
- daily_brief: {query_date} — daily summary statistics

Date rules:
- "last month" = previous calendar month
- "this week" = current Mon-Sun
- "recently" or no time = last 30 days
- "Feb 2024" = 2024-02-01 to 2024-02-29
- "2024年1月15日" = 2024-01-15
- "2024年1月" = 2024-01-01 to 2024-01-31

Off-topic detection:
- If the user says "hello", "hi", "thanks", or anything completely unrelated to geopolitical events, return:
  {"thinking": "User is greeting or off-topic", "intent": "off_topic", "time_range": null, "steps": [], "visualizations": [], "report_prompt": null}

Rules:
- Always include "thinking" — explain your tool selection clearly.
- Max 2 steps. Chain event_detail → similar_events when user asks about a specific event.
- For single-day hot event queries, use "hot_events" tool.
- For date-range top event queries, use "top_events" tool.
- For broad searches, use "events" tool.
- Always include "report" in visualizations.
- report_prompt should ask the AI to analyze and summarize the events found."""


def _extract_json(text: str) -> Optional[Dict]:
    """Extract JSON from LLM response, handling markdown code blocks."""
    text = text.strip()
    
    # Try to find JSON in markdown code block
    match = re.search(r'```(?:json)?\s*(\{.*?)\s*```', text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass
    
    # Try to find raw JSON object
    match = re.search(r'(\{.*\})', text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass
    
    return None


def _normalize_plan(raw: Dict) -> QueryPlan:
    """Normalize raw dict to QueryPlan, handling alias variations."""
    steps = []
    for s in raw.get("steps", []):
        step_type = s.get("type") or s.get("query_type") or "events"
        steps.append(QueryStep(type=step_type, params=s.get("params", {})))
    
    return QueryPlan(
        intent=raw.get("intent", "unknown"),
        thinking=raw.get("thinking"),
        time_range=raw.get("time_range"),
        steps=steps,
        visualizations=raw.get("visualizations", ["event_table", "report"]),
        report_prompt=raw.get("report_prompt"),
    )


class Planner:
    """Generates structured query plans from natural language input."""

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.llm = build_llm(config)

    # Quick off-topic / greeting detection without LLM
    _GREETING_PATTERNS = re.compile(
        r'^(hi+|hello|hey|thanks?|thank you|ok+|bye|goodbye|see you|[?]+)\s*$',
        re.IGNORECASE
    )

    def _rule_based_plan(self, query: str) -> Optional[QueryPlan]:
        """Minimal rule-based guard: only handle obvious off-topic greetings.
        Everything else goes to LLM for intelligent tool selection."""
        q = query.lower().strip()
        if len(q) < 3 or self._GREETING_PATTERNS.match(q):
            return QueryPlan(
                intent="off_topic",
                thinking="User input is a greeting or too short — no tools needed.",
                steps=[],
                visualizations=[],
                report_prompt=None,
            )
        # Let LLM handle all real queries
        return None

    async def plan(self, user_query: str) -> QueryPlan:
        """Generate a query plan from user input."""
        stripped = user_query.strip()
        if self._GREETING_PATTERNS.match(stripped) or len(stripped) < 3:
            print(f"[Planner] Fast off-topic detected for: '{stripped}'", flush=True)
            return QueryPlan(
                intent="off_topic",
                steps=[],
                visualizations=[],
                report_prompt=None,
            )

        # Try rule-based planner first
        fast_plan = self._rule_based_plan(stripped)
        if fast_plan:
            print(f"[Planner] Rule-based plan: {fast_plan.intent} with {len(fast_plan.steps)} steps", flush=True)
            return fast_plan

        messages = [
            SystemMessage(content=PLANNER_SYSTEM_PROMPT),
            HumanMessage(content=f'User request: "{user_query}"\n\nRespond with ONLY raw JSON:'),
        ]
        
        try:
            response = await asyncio.wait_for(self.llm.ainvoke(messages), timeout=35.0)
            content = response.content if hasattr(response, "content") else str(response)
            print(f"[Planner] raw response length: {len(content)}", flush=True)
            
            raw = _extract_json(content)
            if raw is None:
                raise ValueError(f"Could not extract JSON from response: {content[:200]}...")
            
            plan = _normalize_plan(raw)
            print(f"[Planner] generated plan: {plan.intent} with {len(plan.steps)} steps", flush=True)
            return plan
            
        except asyncio.TimeoutError:
            print(f"[Planner] LLM timeout after 35s, using fallback plan", flush=True)
            return QueryPlan(
                intent="fallback_search",
                thinking="LLM planner timed out. Falling back to broad keyword search.",
                steps=[QueryStep(type="events", params={"query": user_query, "limit": 20})],
                visualizations=["event_table", "report"],
                report_prompt=f"Search results for: {user_query}",
            )
        except Exception as e:
            print(f"[Planner] failed: {e}, using fallback plan", flush=True)
            return QueryPlan(
                intent="fallback_search",
                thinking=f"Planner error: {str(e)[:100]}. Falling back to broad keyword search.",
                steps=[QueryStep(type="events", params={"query": user_query, "limit": 20})],
                visualizations=["event_table", "report"],
                report_prompt=f"Search results for: {user_query}",
            )


# ---------------------------------------------------------------------------
# Report Generator
# ---------------------------------------------------------------------------

REPORT_SYSTEM_PROMPT = """You are GDELT Report Generator. Write a concise executive summary based on structured event data.

Guidelines:
- 2-3 paragraphs max
- Cite specific numbers, dates, actor names
- Highlight patterns and significance
- If data is sparse, say so
- Output ONLY raw JSON matching schema: {"summary": "...", "key_findings": ["...", "..."]}"""


class ReportGenerator:
    """Generates natural language reports from structured JSON data."""

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.llm = build_llm(config)

    async def generate(self, data: Dict[str, Any], prompt: Optional[str] = None) -> ReportResult:
        """Generate a report from query results."""
        # Truncate large data
        data_str = json.dumps(data, default=str, ensure_ascii=False)
        if len(data_str) > 6000:
            data_str = data_str[:6000] + "\n... [truncated]"

        user_prompt = prompt or "Summarize the key insights from this GDELT data."
        messages = [
            SystemMessage(content=REPORT_SYSTEM_PROMPT),
            HumanMessage(content=f"{user_prompt}\n\nData:\n{data_str}\n\nRespond with ONLY raw JSON:"),
        ]
        
        try:
            response = await self.llm.ainvoke(messages)
            content = response.content if hasattr(response, "content") else str(response)
            
            raw = _extract_json(content)
            if raw is None:
                raise ValueError("Could not extract JSON from report response")
            
            return ReportResult(
                summary=raw.get("summary", ""),
                key_findings=raw.get("key_findings", []),
            )
        except Exception as e:
            print(f"[ReportGenerator] failed: {e}", flush=True); raise
            return ReportResult(
                summary="Unable to generate report due to an error. Please review the raw data.",
                key_findings=[],
            )
