"""
GDELT Planner + Report Generator

Planner: Understands user intent and generates a structured query plan.
Report Generator: Summarizes JSON data into natural language insights.

Both use LangChain ChatOpenAI for LLM integration.
"""

import os
import json
import re
import asyncio

from typing import List, Dict, Any, Optional

import httpx
from pydantic import BaseModel, Field
from langchain_core.messages import SystemMessage, HumanMessage
from langchain_openai import ChatOpenAI




# ---------------------------------------------------------------------------
# Data Models
# ---------------------------------------------------------------------------

class QueryStep(BaseModel):
    """A single data query step in the execution plan."""
    type: str = Field(..., description="Query type: dashboard, timeseries, geo, events, overview, top_events, hot_events, daily_brief, news_context, event_detail")
    params: Dict[str, Any] = Field(default_factory=dict, description="Parameters for the query")


class QueryPlan(BaseModel):
    """Structured plan generated by the Planner."""
    intent: str = Field(..., description="Brief description of user intent")
    time_range: Optional[Dict[str, str]] = Field(None, description="Resolved date range {start, end} if applicable")
    steps: List[QueryStep] = Field(..., description="Ordered list of queries to execute")
    visualizations: List[str] = Field(..., description="Recommended visualizations: stats_cards, timeline, map, heatmap, event_table, report")
    report_prompt: Optional[str] = Field(None, description="Optional prompt for AI report generation")


class ReportResult(BaseModel):
    """AI-generated report based on query results."""
    summary: str = Field(..., description="Executive summary")
    key_findings: List[str] = Field(default_factory=list, description="Bullet point key findings")


# ---------------------------------------------------------------------------
# LLM Builder (shared between Planner and Report)
# ---------------------------------------------------------------------------

def build_llm(config: Optional[Dict[str, Any]] = None) -> ChatOpenAI:
    """Initialize LLM from environment or runtime config."""
    cfg = config or {}
    provider = cfg.get("provider", os.getenv("LLM_PROVIDER", "kimi")).lower()

    configs = {
        "kimi": {
            "api_key": cfg.get("api_key", os.getenv("KIMI_CODE_API_KEY", os.getenv("MOONSHOT_API_KEY", ""))),
            "base_url": cfg.get("base_url", os.getenv("LLM_BASE_URL", "https://api.moonshot.cn/v1")),
            "model": cfg.get("model", os.getenv("LLM_MODEL", "kimi-k2-0905-preview")),
        },
        "moonshot": {
            "api_key": cfg.get("api_key", os.getenv("MOONSHOT_API_KEY", "")),
            "base_url": cfg.get("base_url", os.getenv("LLM_BASE_URL", "https://api.moonshot.cn/v1")),
            "model": cfg.get("model", os.getenv("LLM_MODEL", "kimi-k2-0905-preview")),
        },
        "claude": {
            "api_key": cfg.get("api_key", os.getenv("ANTHROPIC_API_KEY", "")),
            "base_url": cfg.get("base_url", os.getenv("LLM_BASE_URL", "https://api.anthropic.com/v1")),
            "model": cfg.get("model", os.getenv("LLM_MODEL", "claude-3-5-sonnet-20241022")),
        },
        "openai": {
            "api_key": cfg.get("api_key", os.getenv("OPENAI_API_KEY", "")),
            "base_url": cfg.get("base_url", os.getenv("LLM_BASE_URL", "https://api.openai.com/v1")),
            "model": cfg.get("model", os.getenv("LLM_MODEL", "gpt-4o")),
        },
    }

    provider_cfg = configs.get(provider, configs["kimi"])

    if not provider_cfg["api_key"]:
        raise ValueError(f"API key not set for provider: {provider}")

    # Kimi Coding API headers
    async def _inject_claude_headers(request: httpx.Request):
        request.headers["User-Agent"] = "claude-code/1.0"
        request.headers["X-Client-Name"] = "claude-code"

    http_async_client = httpx.AsyncClient(
        event_hooks={"request": [_inject_claude_headers]}
    )

    return ChatOpenAI(
        api_key=provider_cfg["api_key"],
        base_url=provider_cfg["base_url"],
        model=provider_cfg["model"],
        temperature=0.1,
        max_tokens=2048,
        http_async_client=http_async_client,
    )


# ---------------------------------------------------------------------------
# Planner
# ---------------------------------------------------------------------------

PLANNER_SYSTEM_PROMPT = """You are GDELT Planner. Your ONLY job is to output a raw JSON object. Do NOT write markdown, do NOT add explanations, do NOT wrap in code blocks. Output pure JSON only.

The JSON must match this exact schema:
{
  "intent": "short description of what user wants",
  "time_range": {"start": "YYYY-MM-DD", "end": "YYYY-MM-DD"} or null,
  "steps": [
    {"type": "QUERY_TYPE", "params": {...}}
  ],
  "visualizations": ["stats_cards", "timeline", "map", "heatmap", "event_table", "report"],
  "report_prompt": "optional prompt for report generation"
}

Valid query types for "type" field:
- dashboard: {start_date, end_date}
- overview: {region, time_range} — region like "USA", "Canada"; time_range like "week", "month"
- top_events: {start_date, end_date, region_filter, event_type, top_n}
- events: {query, time_hint, location_hint, limit}
- timeseries: {start_date, end_date, granularity} — granularity: "day", "week", "month"
- geo: {start_date, end_date, precision} — precision MUST be an integer 1-4 (1=country, 2=region, 3=city area, 4=street). NEVER use "city" or other strings.
- daily_brief: {date}
- news_context: {query, n_results}

Date rules:
- "last month" = previous calendar month
- "this week" = current Mon-Sun
- "recently" or no time = last 30 days
- "Feb 2024" = 2024-02-01 to 2024-02-29

Off-topic detection:
- If the user says "hello", "hi", "thanks", or anything completely unrelated to geopolitical events, return:
  {"intent": "off_topic", "time_range": null, "steps": [], "visualizations": [], "report_prompt": null}
- Do NOT generate a default search for greetings or irrelevant input.

Rules:
- Max 3 steps. Prefer dashboard + timeseries.
- Always include "report" in visualizations unless user says "just show data".
- Do NOT use event_detail or news_context unless specifically asked.
- For geo precision, ONLY integers 1-4 are allowed."""


def _extract_json(text: str) -> Optional[Dict]:
    """Extract JSON from LLM response, handling markdown code blocks."""
    text = text.strip()
    
    # Try to find JSON in markdown code block
    match = re.search(r'```(?:json)?\s*(\{.*?)\s*```', text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass
    
    # Try to find raw JSON object
    match = re.search(r'(\{.*\})', text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass
    
    return None


def _normalize_plan(raw: Dict) -> QueryPlan:
    """Normalize raw dict to QueryPlan, handling alias variations."""
    steps = []
    for s in raw.get("steps", []):
        step_type = s.get("type") or s.get("query_type") or "events"
        steps.append(QueryStep(type=step_type, params=s.get("params", {})))
    
    return QueryPlan(
        intent=raw.get("intent", "unknown"),
        time_range=raw.get("time_range"),
        steps=steps,
        visualizations=raw.get("visualizations", ["event_table", "report"]),
        report_prompt=raw.get("report_prompt"),
    )


class Planner:
    """Generates structured query plans from natural language input."""

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.llm = build_llm(config)

    # Quick off-topic / greeting detection without LLM
    _GREETING_PATTERNS = re.compile(
        r'^(hi+|hello|hey|thanks?|thank you|ok+|bye|goodbye|see you|[?]+)\s*$',
        re.IGNORECASE
    )

    def _rule_based_plan(self, query: str) -> Optional[QueryPlan]:
        """Fast rule-based planner for common query patterns. Returns None if no match."""
        q = query.lower().strip()
        if len(q) < 3 or self._GREETING_PATTERNS.match(q):
            return QueryPlan(intent="off_topic", steps=[], visualizations=[], report_prompt=None)

        # Extract date patterns
        import re as _re
        year_month = _re.search(r'(\d{4})-?(\d{2})', q)
        month_year = _re.search(r'(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+(\d{4})', q, _re.IGNORECASE)
        
        start_date, end_date = None, None
        if year_month:
            y, m = year_month.groups()
            from calendar import monthrange
            _, last_day = monthrange(int(y), int(m))
            start_date = f"{y}-{m}-01"
            end_date = f"{y}-{m}-{last_day:02d}"
        elif month_year:
            month_map = {'jan': '01', 'feb': '02', 'mar': '03', 'apr': '04', 'may': '05', 'jun': '06',
                        'jul': '07', 'aug': '08', 'sep': '09', 'oct': '10', 'nov': '11', 'dec': '12'}
            m = month_map.get(month_year.group(1).lower()[:3], '01')
            y = month_year.group(2)
            from calendar import monthrange
            _, last_day = monthrange(int(y), int(m))
            start_date = f"{y}-{m}-01"
            end_date = f"{y}-{m}-{last_day:02d}"
        
        if not start_date:
            # Default to last 30 days
            from datetime import datetime, timedelta
            end_dt = datetime.now().date()
            start_dt = end_dt - timedelta(days=30)
            start_date = start_dt.strftime('%Y-%m-%d')
            end_date = end_dt.strftime('%Y-%m-%d')

        # Fingerprint / event ID detection (e.g. US-20240101-VIR-MASS-1149261787)
        fingerprint_match = _re.search(r'\b([A-Z]{2}-\d{8}-[A-Z]{3}-[A-Z]+-\d+)\b', query, _re.IGNORECASE)
        if fingerprint_match:
            fp = fingerprint_match.group(1)
            return QueryPlan(
                intent="event_detail_lookup",
                time_range=None,
                steps=[QueryStep(type="event_detail", params={"fingerprint": fp})],
                visualizations=["event_table"],
                report_prompt=f"Show details for event {fp}."
            )

        # EVT-ID format (e.g. EVT-2024-01-01-1149261787)
        evt_match = _re.search(r'\b(EVT-\d{4}-\d{2}-\d{2}-\d+)\b', query, _re.IGNORECASE)
        if evt_match:
            fp = evt_match.group(1)
            return QueryPlan(
                intent="event_detail_lookup",
                time_range=None,
                steps=[QueryStep(type="event_detail", params={"fingerprint": fp})],
                visualizations=["event_table"],
                report_prompt=f"Show details for event {fp}."
            )

        # Pattern matching
        if 'dashboard' in q or 'overview' in q or 'summary' in q:
            return QueryPlan(
                intent="dashboard_summary",
                time_range={"start": start_date, "end": end_date},
                steps=[QueryStep(type="dashboard", params={"start_date": start_date, "end_date": end_date})],
                visualizations=["stats_cards", "timeline", "report"],
                report_prompt=f"Summarize the geopolitical dashboard for {start_date} to {end_date}."
            )

        if 'map' in q or 'heatmap' in q or 'where' in q or 'geo' in q or 'location' in q:
            return QueryPlan(
                intent="geographic_analysis",
                time_range={"start": start_date, "end": end_date},
                steps=[QueryStep(type="geo", params={"start_date": start_date, "end_date": end_date, "precision": 2})],
                visualizations=["map", "report"],
                report_prompt=f"Analyze geographic event distribution for {start_date} to {end_date}."
            )

        if 'conflict' in q or 'cooperation' in q or 'trend' in q or 'trends' in q:
            region = "USA"
            if 'canada' in q: region = "CA"
            if 'mexico' in q: region = "MX"
            return QueryPlan(
                intent="conflict_trend_analysis",
                time_range={"start": start_date, "end": end_date},
                steps=[
                    QueryStep(type="timeseries", params={"start_date": start_date, "end_date": end_date, "granularity": "day"}),
                    QueryStep(type="top_events", params={"start_date": start_date, "end_date": end_date, "region_filter": region, "event_type": "conflict", "top_n": 10}),
                    QueryStep(type="geo", params={"start_date": start_date, "end_date": end_date, "precision": 2}),
                ],
                visualizations=["timeline", "heatmap", "event_table", "report"],
                report_prompt=f"Analyze conflict and cooperation trends in {region} for {start_date} to {end_date}."
            )

        if 'event' in q or 'happened' in q or 'news' in q or 'what' in q:
            return QueryPlan(
                intent="event_search",
                time_range={"start": start_date, "end": end_date},
                steps=[QueryStep(type="events", params={"query": query, "limit": 20})],
                visualizations=["event_table", "report"],
                report_prompt=f"Summarize key events matching: {query}"
            )

        return None

    async def plan(self, user_query: str) -> QueryPlan:
        """Generate a query plan from user input."""
        stripped = user_query.strip()
        if self._GREETING_PATTERNS.match(stripped) or len(stripped) < 3:
            print(f"[Planner] Fast off-topic detected for: '{stripped}'", flush=True)
            return QueryPlan(
                intent="off_topic",
                steps=[],
                visualizations=[],
                report_prompt=None,
            )

        # Try rule-based planner first
        fast_plan = self._rule_based_plan(stripped)
        if fast_plan:
            print(f"[Planner] Rule-based plan: {fast_plan.intent} with {len(fast_plan.steps)} steps", flush=True)
            return fast_plan

        messages = [
            SystemMessage(content=PLANNER_SYSTEM_PROMPT),
            HumanMessage(content=f'User request: "{user_query}"\n\nRespond with ONLY raw JSON:'),
        ]
        
        try:
            response = await asyncio.wait_for(self.llm.ainvoke(messages), timeout=35.0)
            content = response.content if hasattr(response, "content") else str(response)
            print(f"[Planner] raw response length: {len(content)}", flush=True)
            
            raw = _extract_json(content)
            if raw is None:
                raise ValueError(f"Could not extract JSON from response: {content[:200]}...")
            
            plan = _normalize_plan(raw)
            print(f"[Planner] generated plan: {plan.intent} with {len(plan.steps)} steps", flush=True)
            return plan
            
        except asyncio.TimeoutError:
            print(f"[Planner] LLM timeout after 15s, using fallback plan", flush=True)
            return QueryPlan(
                intent="fallback_search",
                steps=[QueryStep(type="events", params={"query": user_query, "limit": 20})],
                visualizations=["event_table", "report"],
                report_prompt=f"Search results for: {user_query}",
            )
        except Exception as e:
            print(f"[Planner] failed: {e}, using fallback plan", flush=True)
            return QueryPlan(
                intent="fallback_search",
                steps=[QueryStep(type="events", params={"query": user_query, "limit": 20})],
                visualizations=["event_table", "report"],
                report_prompt=f"Search results for: {user_query}",
            )


# ---------------------------------------------------------------------------
# Report Generator
# ---------------------------------------------------------------------------

REPORT_SYSTEM_PROMPT = """You are GDELT Report Generator. Write a concise executive summary based on structured event data.

Guidelines:
- 2-3 paragraphs max
- Cite specific numbers, dates, actor names
- Highlight patterns and significance
- If data is sparse, say so
- Output ONLY raw JSON matching schema: {"summary": "...", "key_findings": ["...", "..."]}"""


class ReportGenerator:
    """Generates natural language reports from structured JSON data."""

    def __init__(self, config: Optional[Dict[str, Any]] = None):
        self.llm = build_llm(config)

    async def generate(self, data: Dict[str, Any], prompt: Optional[str] = None) -> ReportResult:
        """Generate a report from query results."""
        # Truncate large data
        data_str = json.dumps(data, default=str, ensure_ascii=False)
        if len(data_str) > 6000:
            data_str = data_str[:6000] + "\n... [truncated]"

        user_prompt = prompt or "Summarize the key insights from this GDELT data."
        messages = [
            SystemMessage(content=REPORT_SYSTEM_PROMPT),
            HumanMessage(content=f"{user_prompt}\n\nData:\n{data_str}\n\nRespond with ONLY raw JSON:"),
        ]
        
        try:
            response = await self.llm.ainvoke(messages)
            content = response.content if hasattr(response, "content") else str(response)
            
            raw = _extract_json(content)
            if raw is None:
                raise ValueError("Could not extract JSON from report response")
            
            return ReportResult(
                summary=raw.get("summary", ""),
                key_findings=raw.get("key_findings", []),
            )
        except Exception as e:
            print(f"[ReportGenerator] failed: {e}", flush=True); raise
            return ReportResult(
                summary="Unable to generate report due to an error. Please review the raw data.",
                key_findings=[],
            )
